name: CD - Deploy Sistema de Notas

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'

jobs:
  deploy-testnet:
    name: Deploy na Testnet
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Compilar contratos
        run: npm run compile

      - name: Deploy na Testnet (Sepolia)
        run: npm run deploy:testnet
        env:
          SEPOLIA_URL: ${{ secrets.SEPOLIA_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - name: Criar relatório de deploy
        if: success()
        run: |
          echo "# Relatório de Deploy" > deployment-report.md
          echo "Data: $(date)" >> deployment-report.md
          echo "Tag: ${GITHUB_REF#refs/tags/}" >> deployment-report.md
          echo "Commit: ${{ github.sha }}" >> deployment-report.md
          # Nota: Em um cenário real, aqui você poderia capturar e adicionar os endereços de contratos deployados

      - name: Upload relatório de deploy
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deployment-report
          path: deployment-report.md
