name: CD - Deploy Sistema de Notas

on:
  push:
    #branches: [ main, master, test ]
    #tags:
    #  - 'v*'

jobs:
  deploy-testnet:
    name: Deploy na Testnet
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  # Atualizado de v3 para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Atualizado de v3 para v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Compilar contratos
        run: npm run compile

      - name: Deploy na Testnet (Sepolia)
        run: npm run deploy:testnet
        env:
          SEPOLIA_URL: ${{ secrets.SEPOLIA_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - name: Criar diretório para relatórios
        run: mkdir -p deployment-reports

      - name: Criar relatório de deploy
        if: success()
        run: |
          echo "# Relatório de Deploy" > deployment-reports/deployment-report.md
          echo "Data: $(date)" >> deployment-reports/deployment-report.md
          echo "Tag: ${GITHUB_REF#refs/tags/}" >> deployment-reports/deployment-report.md
          echo "Commit: ${{ github.sha }}" >> deployment-reports/deployment-report.md
          
          # Adicionar endereços de contratos deployados se disponíveis
          if [ -f "test-results/deploy-addresses.json" ]; then
            echo "## Endereços dos Contratos" >> deployment-reports/deployment-report.md
            echo '```json' >> deployment-reports/deployment-report.md
            cat test-results/deploy-addresses.json >> deployment-reports/deployment-report.md
            echo '```' >> deployment-reports/deployment-report.md
          fi

      - name: Upload relatório de deploy
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-report
          path: deployment-reports/
