name: Segurança - Análise de Smart Contracts(teste)

on:
  push:
    branches: [ main, master, develop]

    # "Patch" retirado para teste

  workflow_dispatch:

jobs:
  security-scan:
    name: Verificação de Segurança
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Slither
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer

      - name: Compilar contratos
        run: npm run compile

      - name: Executar Slither
        id: slither
        run: |
          mkdir -p reports
          slither . --exclude-dependencies --exclude-informational --json reports/slither.json
        continue-on-error: true

      - name: Executar Solhint (Linting)
        id: solhint
        run: |
          npm install -g solhint
          solhint "**/*.sol" -f json > reports/solhint.json || true
        continue-on-error: true

      - name: Resumo de Segurança
        run: |
          echo "## Resumo da Análise de Segurança" >> $GITHUB_STEP_SUMMARY
          echo "- Análise estática: Concluída" >> $GITHUB_STEP_SUMMARY
          echo "- Linting de código: Concluído" >> $GITHUB_STEP_SUMMARY
          echo "Verifique os artefatos para detalhes completos." >> $GITHUB_STEP_SUMMARY

      - name: Publicar relatórios
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: reports/
          retention-days: 14
